//{{NO_DEPENDENCIES}}
// fichier Include Microsoft Visual C++.
// Utilisé par DeTeCt-MFC.rc
//
#define IDOK2                           2
#define IDOK3                           4
#define IDABORT2                        5
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DETECTMFC_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       130
#define IDD_PREFERENCES                 132
#define IDD_SETINGS                     132
#define IDD_SETTINGS_ADVANCED           132
#define IDD_SENDLOGDIALOG               140
#define IDD_PROGRESSDIALOG              143
#define IDD_USER_PREFERENCES            144
#define IDD_SETTINGS_USER               144
#define IDI_ICON_AS                     148
#define IDB_PNG1                        149
#define IDB_FIRECAPTURE                 178
#define IDB_GENIKA                      180
#define IDB_LUCAMRECORDER               181
#define IDB_PARAMETERS                  182
#define IDB_PLXCAPTURE                  183
#define IDB_SHARPCAP                    184
#define IDB_GEMINI                      187
#define IDB_BITMAP1                     188
#define IDB_ASICAP                      188
#define IDI_ICON_INFO                   189
#define IDB_BITMAP2                     193
#define IDB_CRITICAL                    193
#define IDB_BITMAP3                     194
#define IDB_BITMAP4                     195
#define IDB_INFORMATION                 195
#define IDB_BITMAP5                     196
#define IDB_QUESTION                    196
#define IDI_ICON_EXCLAMATION            203
#define IDI_ICON_EXCLAMATION_SMALL      210
#define IDB_EXCLAMATION_SMALL           211
#define IDI_ICON2                       215
#define IDI_CRITICAL                    215
#define IDC_EDIT1                       1004
#define IDC_EDIT2                       1005
#define IDC_EDIT3                       1006
#define IDC_EDIT4                       1007
#define IDC_SPLIT1                      1009
#define IDC_EDIT6                       1009
#define IDC_SPIN1                       1010
#define IDC_SPIN2                       1011
#define IDC_SPIN3                       1012
#define IDC_SPIN4                       1013
#define IDC_SPIN5                       1014
#define IDC_RICHEDIT21                  1015
#define IDC_SPIN6                       1015
#define IDC_CHECK1                      1016
#define IDC_CHECK2                      1017
#define IDC_CHECK3                      1018
#define IDC_CHECK4                      1019
#define IDC_CHECK5                      1020
#define IDC_CHECK6                      1021
#define IDC_CHECK7                      1022
#define IDC_CHECK8                      1023
#define IDC_CHECK9                      1024
#define IDC_SPIN7                       1026
#define IDC_SPIN8                       1028
#define IDC_SPIN9                       1030
#define IDC_EDIT10                      1031
#define IDC_SPIN10                      1032
#define IDC_EDIT11                      1033
#define IDC_SPIN11                      1034
#define IDC_EDIT12                      1035
#define IDC_SPIN12                      1036
#define IDC_EDIT13                      1037
#define IDC_SPIN13                      1038
#define IDC_EDIT14                      1039
#define IDC_SPIN14                      1040
#define IDC_EDIT15                      1041
#define IDC_SPIN15                      1042
#define IDC_CHECK11                     1044
#define IDC_CHECK12                     1045
#define IDC_CHECK13                     1046
#define IDC_CHECK14                     1047
#define IDC_COMBO1                      1048
#define IDC_CHECK15                     1049
#define IDC_EDIT16                      1050
#define IDC_SPIN16                      1051
#define IDC_CHECK16                     1052
#define IDC_EDIT17                      1053
#define IDC_SPIN17                      1054
#define IDC_BUTTON1                     1055
#define IDC_LIST1                       1056
#define IDC_PROGRESS1                   1057
#define IDC_PROGRESS2                   1058
#define IDC_MFCLINK1                    1060
#define IDC_MFCLINK2                    1061
#define IDC_MFCLINK3                    1062
#define IDC_STATICS                     1066
#define IDC_STATICF                     1068
#define IDC_STATICI                     1069
#define IDC_STATICF3                    1070
#define IDC_STATICF2                    1070
#define IDC_COMBO2                      1071
#define IDC_FRAME                       1073
#define IDC_FRAME_MINSIZE               1074
#define IDC_CHECK10                     1075
#define IDC_IMPACTLOW                   1076
#define IDC_CHECK17                     1076
#define IDC_CHECK_CLEAN                 1076
#define IDC_CHECK18                     1077
#define IDC_STATIC_TOTALPROGRESS        1077
#define IDC_IMPACTHIGH                  1078
#define IDC_NOREPROC                    1078
#define IDC_IMPACTNULL                  1079
#define IDC_STATIC_FILENAME             1080
#define IDC_STATIC_COMPUTING            1081
#define IDC_MFCLINK_DETECTIMAGES        1082
#define IDC_MFCLINK_ZIPFILE             1083
#define IDC_CHECK_AS                    1085
#define IDC_CHECK_DARK                  1086
#define IDC_CHECK_ACQUISITIONLOG        1087
#define IDC_CHECK_SER                   1088
#define IDC_CHECK_SERTIMESTAMP          1089
#define IDC_CHECK_FITS                  1090
#define IDC_CHECK_FILEINFO              1091
#define IDC_STATIC_ACQUISITIONSW        1092
#define IDC_CHECK_EXECAS                1093
#define IDC_STATIC_INSTANCE             1094
#define IDC_BUTTON_CHECKRESULTS         1095
#define IDC_MFCLINK_DETECTLOG           1096
#define IDC_STATICPROBA                 1097
#define IDC_STATIC_COMPUTING2           1098
#define IDC_STATIC_DURATION             1098
#define ID_PREFOK                       1098
#define IDC_MFCLINK_DETECTLOG2          1099
#define IDC_CHECK_AUTO                  1100
#define IDC_CHECK_EXIT                  1101
#define IDC_CHECK_EXIT2                 1102
#define IDC_CHECK_SHUTDOWN              1102
#define IDC_SPIN_INSTANCES              1103
#define IDC_STATIC_MAXINST              1104
#define ID_PREFOK_USER                  1105
#define IDC_RESET_USER                  1107
#define IDC_CHECK_FLAT                  1108
#define IDC_CHECK_DEBUG                 1109
#define IDC_CHECK_MEAN_IMG              1110
#define IDC_CHECK_DETECTION_IMG         1111
#define ID_FILE_OPENFOLDER              32771
#define ID_SETTINGS_PREFERENCES         32772
#define ID_HELP_EXIT                    32773
#define ID_HELP_MANUAL                  32774
#define ID_EXIT_QUIT                    32775
#define ID_FILE_EXIT                    32776
#define ID_FILE_OPENFILE                32777
#define ID_HELP_TUTORIAL                32778
#define ID_HELP_DOCUMENTATION           32779
#define ID_HELP_CHECKSFORUPDATE         32781
#define ID_HELP_PROJECTRESULTS          32782
#define ID_FILE_RESETFILELIST           32783
#define ID_FILE_RESETEXECUTIONLOG       32784
#define ID_FILE_CLEAREXECUTIONLOG       32785
#define ID_FILE_CLEARIMPACTFILES        32786
#define ID_HELP_HISTORY                 32788
#define ID_Menu                         32789
#define ID_SETTINGS_USER                32790
#define ID_SETTINGS_ADVANCED            32791

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        216
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1112
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
